// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorKind } from "./ErrorKind.ts";

export interface ErrorIR { kind: ErrorKind, source: string, }