// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CausedBy } from "./CausedBy.ts";
import type { EventInner } from "./EventInner.ts";
import type { EventLevel } from "./EventLevel.ts";
import type { Snowflake } from "./Snowflake.ts";

export interface ClientEvent { event_inner: EventInner, details: string, snowflake: Snowflake, level: EventLevel, caused_by: CausedBy, }
