// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface GenericSetupConfigPrimitive { name: string, description: string | null, port: number, auto_start: boolean | null, restart_on_crash: boolean | null, timeout_last_left: number | null, timeout_no_activity: number | null, start_on_connection: boolean | null, }
