// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExitStatus } from "./ExitStatus.ts";
import type { TaskEntry } from "./TaskEntry.ts";

export interface HistoryEntry { task: TaskEntry, exit_status: ExitStatus, }
