// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InstanceOperation = "GetMinRam" | "GetMaxRam" | "GetRestartOnCrash" | "GetTimeoutLastLeft" | "GetTimeoutNoActivity" | "GetStartOnConnection" | "GetBackupPeriod" | "SetMinRam" | "SetMaxRam" | "SetPort" | "SetRestartOnCrash" | "SetTimeoutLastLeft" | "SetTimeoutNoActivity" | "SetStartOnConnection" | "SetBackupPeriod" | "RunMacro" | "GetPlayerCount" | "GetMaxPlayerCount" | "GetPlayerList" | "LoadResource" | "UnloadResource" | "DeleteResource";
