// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstanceOperation } from "./InstanceOperation.ts";

export interface InstanceManifest { supported_operations: Array<InstanceOperation>, settings: Array<string>, }
