// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JwtToken } from "./JwtToken.ts";
import type { PublicUser } from "./PublicUser.ts";

export interface LoginReply { token: JwtToken, user: PublicUser, }
