// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExitStatus } from "./ExitStatus.ts";

export type MacroEventInner = { type: "Started" } | { type: "MainModuleExecuted" } | { type: "Detach" } | { type: "Stopped", exit_status: ExitStatus, };
