// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MinecraftFlavour } from "./MinecraftFlavour.ts";

export interface MinecraftSetupConfigPrimitive { name: string, version: string, flavour: MinecraftFlavour, port: number, cmd_args: Array<string> | null, description: string | null, min_ram: number | null, max_ram: number | null, auto_start: boolean | null, restart_on_crash: boolean | null, timeout_last_left: number | null, timeout_no_activity: number | null, start_on_connection: boolean | null, backup_period: number | null, }
