// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Snowflake } from "./Snowflake.ts";

export type ProgressionEventID = Snowflake;