// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstanceInfo } from "./InstanceInfo.ts";
import type { InstanceUuid } from "./InstanceUuid.ts";

export type ProgressionEndValue = { type: "InstanceCreation" } & InstanceInfo | { type: "InstanceDelete", instance_uuid: InstanceUuid, };
