// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProgressionEventInner } from "./ProgressionEventInner.ts";
import type { Snowflake } from "./Snowflake.ts";

export interface ProgressionEvent { event_id: Snowflake, progression_event_inner: ProgressionEventInner, }
