// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserId } from "./UserId.ts";
import type { UserPermission } from "./UserPermission.ts";

export interface PublicUser { uid: UserId, username: string, is_owner: boolean, is_admin: boolean, permissions: UserPermission, }
