// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface CopyInstanceFileRequest { relative_paths_source: Array<string>, relative_path_dest: string, }