// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorKind } from "./ErrorKind";
import type { SettingManifest } from "./SettingManifest";

export interface GetConfigResponse { config: Record<string, SettingManifest>, message: string | null, error: ErrorKind | null, }