// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface GlobalSettingsData { core_name: string, safe_mode: boolean, domain: string | null, playit_enabled: boolean, }