// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstanceEventInner } from './InstanceEventInner';
import type { InstanceUuid } from './InstanceUuid';

export interface InstanceEvent {
  instance_uuid: InstanceUuid;
  instance_name: string;
  instance_event_inner: InstanceEventInner;
}
