// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TunnelUuid } from "./TunnelUuid";

export interface PlayitTunnelInfo { local_ip: string, local_port: number, tunnel_id: TunnelUuid, name: string, server_address: string, active: boolean, }