// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserId } from './UserId';
import type { UserPermission } from './UserPermission';

export interface PublicUser {
  uid: UserId;
  username: string;
  is_owner: boolean;
  is_admin: boolean;
  permissions: UserPermission;
}
