// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface SetupProgress {
  current_step: [number, string];
  total_steps: number;
}
