// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SignupStatus = "CodeNotFound" | "CodeExpired" | "UserRejected" | "NotAccepted" | "NotSetup" | "Completed";