// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MacroPID } from "./MacroPID";

export interface TaskEntry { name: string, creation_time: bigint, pid: MacroPID, }