// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorInner } from './ErrorInner';

export interface ClientError {
  inner: ErrorInner;
  detail: string;
}
