// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorInner } from './ErrorInner';


// implement toString
export class ClientError {
  inner: ErrorInner;
  detail: string;
  
  constructor(inner: ErrorInner, detail: string) {
    this.inner = inner;
    this.detail = detail;
  }

  toString(): string {
    // convert camelCase to space separated words
    const inner = this.inner.replace(/([A-Z])/g, ' $1').trim();
    return `${inner}${this.detail ? `: ${this.detail}` : ''}`;
  }
}
