// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstanceEvent } from './InstanceEvent';
import type { UserEvent } from './UserEvent';

export type EventInner =
  | ({ type: 'InstanceEvent' } & InstanceEvent)
  | ({ type: 'UserEvent' } & UserEvent);
