// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DownloadProgress } from './DownloadProgress';
import type { SetupProgress } from './SetupProgress';

export type InstanceEventInner =
  | { type: 'InstanceStarting' }
  | { type: 'InstanceStarted' }
  | { type: 'InstanceStopping' }
  | { type: 'InstanceStopped' }
  | { type: 'InstanceWarning' }
  | { type: 'InstanceError' }
  | { type: 'InstanceCreationFailed' }
  | { type: 'InstanceInput'; message: string }
  | { type: 'InstanceOutput'; message: string }
  | { type: 'SystemMessage'; message: string }
  | { type: 'PlayerChange'; player_list: Array<string> }
  | { type: 'PlayerJoined'; player: string }
  | { type: 'PlayerLeft'; player: string }
  | { type: 'PlayerMessage'; player: string; player_message: string }
  | ({ type: 'Downloading' } & DownloadProgress)
  | ({ type: 'Setup' } & SetupProgress);
