// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstanceState } from './InstanceState';

export interface InstanceInfo {
  uuid: string;
  name: string;
  flavour: string;
  game_type: string;
  description: string;
  port: number;
  state: InstanceState;
  player_count: number | null;
  max_player_count: number | null;
  creation_time: bigint;
  path: string;
}
