// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InstanceEventInner =
  | { type: 'InstanceStarting' }
  | { type: 'InstanceStarted' }
  | { type: 'InstanceStopping' }
  | { type: 'InstanceStopped' }
  | { type: 'InstanceWarning' }
  | { type: 'InstanceError' }
  | { type: 'InstanceInput'; message: string }
  | { type: 'InstanceOutput'; message: string }
  | { type: 'SystemMessage'; message: string }
  | {
      type: 'PlayerChange';
      player_list: Array<string>;
      players_joined: Array<string>;
      players_left: Array<string>;
    }
  | { type: 'PlayerMessage'; player: string; player_message: string };
