// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InstanceEventKind =
  | 'InstanceStarting'
  | 'InstanceStarted'
  | 'InstanceStopping'
  | 'InstanceStopped'
  | 'InstanceWarning'
  | 'InstanceError'
  | 'InstanceInput'
  | 'InstanceOutput'
  | 'SystemMessage'
  | 'PlayerChange'
  | 'PlayerMessage';
