// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstanceState } from './InstanceState';
import type { InstanceUuid } from './InstanceUuid';
import type { Player } from './Player';

export type GameType = Record<Games, {variant: GameVariants}>
export type Games = "MinecraftJava";
export type GameVariants = "Vanilla" | "Forge" | "Fabric" | "Paper";

export interface InstanceInfo {
  uuid: InstanceUuid;
  name: string;
  game_type: GameType;
  description: string;
  port: number;
  creation_time: bigint;
  path: string;
  auto_start: boolean;
  restart_on_crash: boolean;
  state: InstanceState;
  player_count: number | null;
  max_player_count: number | null;
  player_list: Array<Player> | null;
}
