// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InstanceSetting =
  | 'uuid'
  | 'name'
  | 'flavour'
  | 'game_type'
  | 'cmd_args'
  | 'description'
  | 'port'
  | 'min_ram'
  | 'max_ram'
  | 'creation_time'
  | 'path'
  | 'auto_start'
  | 'restart_on_crash'
  | 'backup_period';
