// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FabricInstallerVersion } from './FabricInstallerVersion';
import type { FabricLoaderVersion } from './FabricLoaderVersion';
import type { ForgeBuildVersion } from './ForgeBuildVersion';
import type { PaperBuildVersion } from './PaperBuildVersion';

export type MinecraftFlavour =
  | { type: 'vanilla' }
  | {
      type: 'fabric';
      loader_version: FabricLoaderVersion | null;
      installer_version: FabricInstallerVersion | null;
    }
  | { type: 'paper'; build_version: PaperBuildVersion | null }
  | { type: 'spigot' }
  | { type: 'forge'; build_version: ForgeBuildVersion | null };
