// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Permission =
  | 'CanViewInstance'
  | 'CanStartInstance'
  | 'CanStopInstance'
  | 'CanAccessConsole'
  | 'CanChangeSetting'
  | 'CanManageResource'
  | 'CanAccessMacro'
  | 'CanCreateInstance'
  | 'CanDeleteInstance'
  | 'CanManageUser'
  | 'CanManagePermission';
