// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GenericPlayer } from "./GenericPlayer";
import type { InstanceState } from "./InstanceState";
import type { PerformanceReport } from "./PerformanceReport";

export type ProcedureCallResultInner = { String: string } | { Monitor: PerformanceReport } | { State: InstanceState } | { Num: number } | { Player: Array<GenericPlayer> } | "Void";