// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SectionManifest } from "./SectionManifest";

export interface SetupManifest { setting_sections: Record<string, SectionManifest>, }