// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserEventInner } from './UserEventInner';

export interface UserEvent {
  user_id: string;
  user_event_inner: UserEventInner;
}
