// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface UserPermission {
  can_view_instance: Array<string>;
  can_start_instance: Array<string>;
  can_stop_instance: Array<string>;
  can_access_instance_console: Array<string>;
  can_access_instance_setting: Array<string>;
  can_read_instance_resource: Array<string>;
  can_write_instance_resource: Array<string>;
  can_access_instance_macro: Array<string>;
  can_read_instance_file: Array<string>;
  can_write_instance_file: Array<string>;
  can_create_instance: boolean;
  can_delete_instance: boolean;
  can_read_global_file: boolean;
  can_write_global_file: boolean;
  can_manage_permission: boolean;
}
