// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FSEvent } from "./FSEvent.ts";
import type { InstanceEvent } from "./InstanceEvent.ts";
import type { MacroEvent } from "./MacroEvent.ts";
import type { ProgressionEvent } from "./ProgressionEvent.ts";
import type { UserEvent } from "./UserEvent.ts";

export type EventInner = { type: "InstanceEvent" } & InstanceEvent | { type: "UserEvent" } & UserEvent | { type: "MacroEvent" } & MacroEvent | { type: "FSEvent" } & FSEvent | { type: "ProgressionEvent" } & ProgressionEvent;
