// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstanceUuid } from "./InstanceUuid.ts";
import type { ProgressionEndValue } from "./ProgressionEndValue.ts";
import type { ProgressionStartValue } from "./ProgressionStartValue.ts";

export type ProgressionEventInner = { type: "ProgressionStart", progression_name: string, producer_id: InstanceUuid | null, total: number | null, inner: ProgressionStartValue | null, } | { type: "ProgressionUpdate", progress_message: string, progress: number, } | { type: "ProgressionEnd", success: boolean, message: string | null, inner: ProgressionEndValue | null, };
