// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConfigurableValue = { type: "String", value: string } | { type: "Integer", value: number } | { type: "UnsignedInteger", value: number } | { type: "Float", value: number } | { type: "Boolean", value: boolean } | { type: "Enum", value: string };