// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameType } from "./GameType";
import type { InstanceUuid } from "./InstanceUuid";

export interface DotLodestoneConfig { game_type: GameType, uuid: InstanceUuid, creation_time: bigint, }