// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExitStatus } from "./ExitStatus";
import type { TaskEntry } from "./TaskEntry";

export interface HistoryEntry { task: TaskEntry, exit_status: ExitStatus, }