// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExitStatus } from "./ExitStatus";

export type MacroEventInner = { type: "Started", macro_name: string, time: bigint, } | { type: "Detach" } | { type: "Stopped", exit_status: ExitStatus, };