// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstanceUuid } from "./InstanceUuid";
import type { MacroEventInner } from "./MacroEventInner";
import type { MacroPID } from "./MacroPID";

export interface MacroEvent { instance_uuid: InstanceUuid | null, macro_pid: MacroPID, macro_event_inner: MacroEventInner, }