// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionType } from "./ExtensionType";
import type { Permission } from "./Permission";

export interface Manifest { type: ExtensionType, author: string, name: string, version: string, description: string, release_notes: string | null, permission: Permission | null, }