// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TunnelUuid } from "./TunnelUuid";

export interface PlayitTunnelInfo { public_ip: string, public_port: number, tunnel_id: TunnelUuid, }