// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlayitggRunnerEventInner } from "./PlayitggRunnerEventInner";

export interface PlayitggRunnerEvent { playitgg_runner_event_inner: PlayitggRunnerEventInner, }