// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PortType } from "./PortType";

export interface PlayitTunnelParams { local_port: number, port_type: PortType, }