// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserEventInner } from "./UserEventInner";
import type { UserId } from "./UserId";

export interface UserEvent { user_id: UserId, user_event_inner: UserEventInner, }