// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ZipRequest { target_relative_paths: Array<string>, destination_relative_path: string, }