// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CausedBy = { type: "User", user_id: string, user_name: string, } | { type: "Instance", instance_uuid: string, } | { type: "Macro", macro_pid: number, } | { type: "System" } | { type: "Unknown" };