// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CausedBy } from "./CausedBy";
import type { EventInner } from "./EventInner";
import type { EventLevel } from "./EventLevel";

export interface ClientEvent { event_inner: EventInner, details: string, snowflake: bigint, snowflake_str: string, level: EventLevel, caused_by: CausedBy, }