// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConfigurableValue = { type: "String" } & string | { type: "Integer" } & number | { type: "UnsignedInteger" } & number | { type: "Float" } & number | { type: "Boolean" } & boolean | { type: "Enum" } & string;