// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConfigurableValue = { String: string } | { Integer: number } | { UnsignedInteger: number } | { Float: number } | { Boolean: boolean } | { Enum: string };