// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventInner } from "./EventInner";

export interface Event { event_inner: EventInner, instance_uuid: string, instance_name: string, details: string, }