// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FSOperation } from "./FSOperation";
import type { FSTarget } from "./FSTarget";

export interface FSEvent { operation: FSOperation, target: FSTarget, }