// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstanceUuid } from "./InstanceUuid";

export interface GenericSetupConfig { game_type: string, uuid: InstanceUuid, name: string, description: string, port: number, auto_start: boolean, restart_on_crash: boolean, started_count: number, }