// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstanceEventInner } from "./InstanceEventInner";

export interface InstanceEvent { instance_uuid: string, instance_name: string, instance_event_inner: InstanceEventInner, }