// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameType } from "./GameType";

export type InstanceGameType = "MinecraftVanilla" | "MinecraftForge" | "MinecraftFabric" | "MinecraftPaper" | "MinecraftSpigot" | "MinecraftBedrock" | { Generic: { game: string, game_type: GameType, } };