// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MacroEventInner } from "./MacroEventInner";

export interface MacroEvent { instance_uuid: string, macro_uuid: string, macro_event_inner: MacroEventInner, }