// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SectionManifestValue } from "./SectionManifestValue";

export interface ManifestValue { setting_sections: Record<string, SectionManifestValue>, }