// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface MinecraftVersions { old_alpha: Array<string>, snapshot: Array<string>, release: Array<string>, }