// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MinecraftFlavour = "vanilla" | { fabric: { loader_version: string | null, installer_version: string | null, } } | { paper: { build_version: bigint | null, } } | "spigot" | { forge: { build_version: string | null, } };