// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProcedureCallInner } from "./ProcedureCallInner";

export interface ProcedureCall { id: bigint, inner: ProcedureCallInner, }