// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProcedureCallKind = "SetupInstance" | "StartInstance" | "StopInstance" | "RestartInstance" | "KillInstance" | "GetState" | "SendCommand" | "Monitor" | "GetPlayerCount" | "GetPlayerList";