// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorIR } from "./ErrorIR";
import type { ProcedureCallKind } from "./ProcedureCallKind";
import type { ProcedureCallResultInner } from "./ProcedureCallResultInner";

export interface ProcedureCallResultIR { id: bigint, success: boolean, procedure_call_kind: ProcedureCallKind, inner: ProcedureCallResultInner | null, error: ErrorIR | null, }