// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CausedBy } from "./CausedBy";
import type { GenericSetupConfig } from "./GenericSetupConfig";

export type ProcedureCallInner = { type: "SetupInstance", config: GenericSetupConfig, path: string, } | { type: "StartInstance", caused_by: CausedBy, } | { type: "StopInstance", caused_by: CausedBy, } | { type: "RestartInstance", caused_by: CausedBy, } | { type: "KillInstance", caused_by: CausedBy, } | { type: "GetState" } | { type: "SendCommand", command: string, caused_by: CausedBy, } | { type: "Monitor" } | { type: "GetPlayerCount" } | { type: "GetPlayerList" };