// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProgressionEndValue } from "./ProgressionEndValue";

export type ProgressionEventInner = { type: "ProgressionStart", progression_name: string, producer_id: string, total: number | null, } | { type: "ProgressionUpdate", progress_message: string | null, progress: number, } | { type: "ProgressionEnd", success: boolean, message: string | null, value: ProgressionEndValue | null, };