// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProgressionEventInner } from "./ProgressionEventInner";

export interface ProgressionEvent { event_id: string, progression_event_inner: ProgressionEventInner, }