use std::{fs, fs::File};
use std::collections::HashMap;
use std::io::prelude::*;
use mongodb::sync::Client;
use rocket::State;
use rocket::fairing::Result;
use crate::MyManagedState;
use crate::instance::*;
use crate::util;
pub struct InstanceManager{
    instance_collection : HashMap<String, ServerInstance>,
    avail_ports : Vec<u16>,
    path : String, // must end with /
    mongodb : Client,
}


// TODO: DB IO
impl InstanceManager {
    pub fn new(path : String, mongodb : Client) -> InstanceManager {
        InstanceManager{
            instance_collection : HashMap::new(),
            path,
            mongodb,
            avail_ports : vec![]
        }
    }
    // TODO: server.properties 
    pub async fn create_instance(&mut self, name : String, version : String, config : Option<InstanceConfig>, state: &State<MyManagedState>) -> Result<(), String> {
        if self.check_if_name_exists(&name) {
            return Err(format!("{} already exists as an instance", name));
        }
        fs::create_dir(self.path.as_str()).map_err(|e| e.to_string())?;
        let url = util::get_vanilla_version_url(version)?;
        let instance = ServerInstance::new(config, format!("{}{}", self.path, name), name.clone());
        util::download_file(url.as_str(), format!("{}{}",self.path, name).as_str(), state, instance.uuid.as_str()).await?; // TODO: get rid of await
        let mut eula_file = File::create("eula.txt").map_err(|e| e.to_string())?;
        eula_file.write_all(b"#generated by Lodestone\neula=true\n").map_err(|e| e.to_string())?;
        self.instance_collection.insert(instance.uuid.clone(), instance).ok_or("error inserting to hashmap".to_string())?;
        Ok(())
    }

    pub fn delete_instance(&mut self, uuid : String) -> Result<(), String> {
        match self.instance_collection.remove(&uuid) {
            None => Err("instance not found".to_string()),
            Some(instance) => {
                fs::remove_dir_all(format!("{}{}", self.path, instance.name)).map_err(|e| e.to_string())?;
                Ok(())
            }
        }
    }

    pub fn clone_instance(&mut self, uuid : String) -> Result<(), String> {
        for pair in &self.instance_collection {
            if pair.0 == &uuid {
                if self.check_if_name_exists(&format!("{}_copy", &pair.1.name)) {
                    return Err(format!("{}_copy already exists as an instance", &pair.1.name));
                }
            }
        };
        Ok(())
    }

    fn check_if_name_exists(&self, name : &String) -> bool {
        let mut ret = false;
        for pair in &self.instance_collection {
            if &pair.1.name == name {
                ret = true;
                break; 
            }
        }
        ret
    }



}
