// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SectionManifest } from "./SectionManifest.ts";

export interface ConfigurableManifest {
    instance_name: string;
    instance_description: string | null;
    auto_start: boolean;
    restart_on_crash: boolean;
    setting_sections: Record<string, SectionManifest>;
}
