// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface DiskUsage { total_written_bytes: bigint, written_bytes: bigint, total_read_bytes: bigint, read_bytes: bigint, }