// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameType } from "./GameType.ts";
import type { InstanceUuid } from "./InstanceUuid.ts";

export interface DotLodestoneConfig { game_type: GameType, uuid: InstanceUuid, creation_time: bigint, lodestone_version: string, }