// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SectionManifestValue } from "./SectionManifestValue.ts";

export interface ManifestValue {
  auto_start: boolean;
  restart_on_crash: boolean;
  setting_sections: Record<string, SectionManifestValue>;
}
