// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiskUsage } from "./DiskUsage.ts";

export interface PerformanceReport {
  memory_usage: bigint | null;
  disk_usage: DiskUsage | null;
  cpu_usage: number | null;
  start_time: bigint | null;
}
