// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SettingManifest } from "./SettingManifest.ts";

export interface SectionManifest {
  section_id: string;
  name: string;
  description: string;
  settings: Record<string, SettingManifest>;
}
