// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SettingManifestValue } from "./SettingManifestValue.ts";

export interface SectionManifestValue {
  settings: Record<string, SettingManifestValue>;
}
