// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfigurableValue } from "./ConfigurableValue.ts";

export interface SettingManifestValue {
  value: ConfigurableValue | null;
}
